name: Build image from scratch

on:
  push:
    branches:
    - main
    paths:
    - '!**'
  workflow_dispatch:

jobs:
  build-image-from-scratch:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Versioncheck
        run: echo "CSGOVERSION=$(curl -s 'http://api.steampowered.com/ISteamApps/UpToDateCheck/v1?appid=730&version=$1' | jq .response.required_version)" >> $GITHUB_ENV
      - name: Build Linux Image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          tags: |
            flowingspdg/csgo-get5-docker-dev:latest
            flowingspdg/csgo-get5-docker-dev:${{ env.CSGOVERSION }}
          no-cache: true
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: update-remote
        run: ./image-update/update-remote-image.sh
