name: check for latest CS:GO version

on:
  # Run at 37 minutes past every hour
  schedule:
    - cron: '37 * * * *'
  # Enable run manually
  workflow_dispatch:

env:
  DOCKER_REPO: 'apfelwurm/csgo-get5-docker-dev'

jobs:
  check-csgo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fetch metadata from DockerHub
        id: fetch-metadata
        uses: theo-brown/fetch-dockerhub-metadata@v1
        with:
          repository: ${{ env.DOCKER_REPO }}
          tag: latest
      - name: Get installed CSGO version from metadata
        id: csgo-version
        run: |
          INSTALLED_VERSION=$(echo '${{ steps.fetch-metadata.outputs.labels }}' | jq '.csgo_version | tonumber')
          echo "CSGO version installed on DockerHub: $INSTALLED_VERSION"
          echo "::set-output name=version::$INSTALLED_VERSION"
      - name: Check CSGO version against Steam API
        run: |
          VERSION_CHECK=$(curl -s "http://api.steampowered.com/ISteamApps/UpToDateCheck/v1?appid=730&version=${{ steps.csgo-version.outputs.version }}" | jq .response)
          if [ $(echo $VERSION_CHECK | jq .up_to_date) = true ]
          then
            echo "$DOCKER_REPO:latest contains the latest CS:GO version (${{ steps.csgo-version.outputs.version }})."
            echo "CSVERSION=FALSE" >> $GITHUB_ENV
            exit 0
          else
            echo "::error::$DOCKER_REPO:latest contains an outdated CS:GO version \
                  (installed: ${{ steps.csgo-version.outputs.version }} / latest: $(echo $VERSION_CHECK | jq .required_version))."
            echo "CSVERSION=$(echo $VERSION_CHECK | jq .required_version)" >> $GITHUB_ENV
          fi
      - name: create issue from file
        uses: JasonEtco/create-an-issue@v2.8.0
        id: issue
        if: env.CSVERSION != 'FALSE'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: ${{ env.CSVERSION }}
        with:
          filename: .github/templates/issue.newversion.md
          update_existing: true
      - name: checkout
        if: env.CSVERSION != 'FALSE'
        uses: actions/checkout@v3
      - name: Replace Version
        if: env.CSVERSION != 'FALSE'
        run: sed -i 's|ARG CSGO_VERSION=.*$|ARG CSGO_VERSION='${{ env.CSVERSION }}'|g' Dockerfile 
      - uses: EndBug/add-and-commit@v9 
        if: env.CSVERSION != 'FALSE'
        with:
          message: 'Versionupdate to ${{ env.CSVERSION }}'
      # - name: trigger update
      #   if: env.CSVERSION != 'FALSE'
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     repository: ${{ github.repository }}
      #     event-type: update-image
